version: 2.1
jobs:
  build_buildroot:
    machine: true
      steps:
        - run: |
           sudo DEBIAN_FRONTEND=noninteractive apt-get update
           sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libffi-dev libssl-dev python3-dev python3-pyqt5 python3-pyqt5.qtwebengine python3 python3-pip
        - run: pip3 install docker-compose
        - run: sudo usermod -aG docker $USER
        - checkout
        - run: DOCKERDIR=docker__buildroot ./setup.sh ci

  build_yocto:
    machine: true
      steps:
        - run: |
           sudo DEBIAN_FRONTEND=noninteractive apt-get update
           sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libffi-dev libssl-dev python3-dev python3-pyqt5 python3-pyqt5.qtwebengine python3 python3-pip
        - run: pip3 install docker-compose
        - run: sudo usermod -aG docker $USER
        ## yocto (just fetch, due to timeout in ci infrastructure)
        - checkout
        - run: DOCKERDIR=docker__yocto ./setup.sh ci

## parallelization
workflows:
  version: 2
  build:
    jobs:
      - build_buildroot
      - build_yocto
