version: 2.1
jobs:
 build:
   machine: true
   steps:
     - checkout

     # yocto
     - run: cd ./docker__yocto/ && docker build --no-cache --build-arg USER=$USER -t rubuschl/bbb-yocto:123 .
     - run: cd ./docker__yocto && docker run --rm -ti --user=$USER:$USER --workdir=/home/$USER -v $PWD/output:/home/$USER/poky/build -v $PWD/meta-lothars-configs:/home/$USER/poky/meta-lothars-configs rubuschl/bbb-yocto:123

     # buildroot (alpine Linux experiments / musl)
     - run: cd ./docker__buildroot && docker build --no-cache --build-arg USER=$USER -t rubuschl/bbb-buildroot:456 .
     - run: cd ./docker__buildroot && docker run -ti -v $PWD/output:/home/$USER/poky/build -v $PWD/meta-lothars-configs:/home/$USER/poky/meta-lothars-configs --user=$USER:$USER --workdir=/home/$USER rubuschl/bbb-buildroot:456