version: '3.8'

services:
    bbb_yocto:
        container_name: bbb_yocto
        image: ${USER}/bbb_yocto
        build:
            context: build_context
            dockerfile: Dockerfile
            args:
                USER: ${USER}

        user: ${USER}
        stdin_open: true  ## docker run -i
        tty: true         ## docker run -i
        #privileged: true

        environment:
         - USER

        volumes:
         - ~/.gitconfig:/home/${USER}/.gitconfig:ro
         ## actually put in ro, but then known_hosts before
         #- ~/.ssh:/home/${USER}/.ssh:ro
         - ~/.ssh:/home/${USER}/.ssh
         - ./poky:/home/${USER}/poky  ## folder does not need to be around
         - type: bind
           source: ./meta-lothars-configs   ## folder must be around
           target: /home/${USER}/meta-lothars-configs

