version: '3.8'

services:
    bbb_buildroot:
        container_name: bbb_buildroot
        image: ${USER}/bbb_buildroot
        build:
            context: build_context
            dockerfile: Dockerfile
            args:
                USER: "${USER}"
        user: "${USER}"
        stdin_open: true  ## docker run -i
        tty: true         ## docker run -i
        #privileged: true
        environment:
         - USER
        volumes:
         ## folders not need to be around
         - ~/.gitconfig:/home/${USER}/.gitconfig:ro
         - ~/.ssh:/home/${USER}/.ssh
         - ./buildroot:/home/${USER}/buildroot
         ## folder must be around
         - type: bind
           source: ./build_configs
           target: /home/$USER/configs

