version: '3.8'

services:
    bbb_buildroot:
        container_name: bbb_buildroot
        image: ${USER}/bbb_buildroot
        build:
            context: build_context
            dockerfile: Dockerfile
            args:
                USER: "${USER}"
                UID: "${UID}"
                GID: "${GID}"
        user: "${UID}:${GID}"
        stdin_open: true  ## docker run -i
        tty: true         ## docker run -i
        #privileged: true
        environment:
         - USER
        env_file:
         - .env
        volumes:
         - ~/.gitconfig:/home/${USER}/.gitconfig:ro
         ## actually put in ro, but take care of known_hosts before
         #- ~/.ssh:/home/${USER}/.ssh:ro
         - ~/.ssh:/home/${USER}/.ssh
         - ./buildroot:/home/${USER}/buildroot  ## folder does not need to be around

